version: "2.1"

networks:
  communities:
    driver: bridge

services:
  communities-backend:
    image: demo/communities-backend:0.0.1
    networks:
      communities:
        aliases:
        - backend
    ports:
    - "2018:8080"

  communities-frontend:
    image: demo/communities-frontend:0.0.1
    networks:
      communities:
        aliases:
        - frontend
    ports:
    - "2019:80"